export const DEBOUNCE_TIMEOUT = 750
export const GRADIENT_COLORS = ['#007AFF', '#5EA9FF']
export const FONT_COLOR_LIGHT = '#FFF'
export const FONT_COLOR_DARK = '#16191A'
export const BACKGROUND_COLOR_LIGHT = '#FFF'
export const BORDER_COLOR_LIGHT = '#E0E0E0'
export const FONT_WEIGHT_NORMAL = 500
export const PADDING_VERTICAL = 10
export const PADDING_HORIZONTAL = 40
export const BORDER_RADIUS = 25
export const BORDER_WIDTH = 1
